title: "DigiScope"
email: "info@digi-scope.be"
description: ""
domain: "www.digi-scope.be"
url: "https://www.digi-scope.be"
baseurl: ""
instagram_username: digiscope.be
facebook_username: digiscope.be
# twitter_username: jekyllrb
# github_username:  jekyll
google_analytics: "G-GT1SFY9KLM"

# Build settings
theme: minima
plugins:
  - jekyll-feed
